### ISSUE TITLE
exception: Cannot read property '1' of null

### ISSUE THREAD

**Issue by edsu** [edsu/wikichanges#13]
Infrequently I've seen these:

```
/data/project/anon/anon/node_modules/wikichanges/node_modules/irc/lib/parse_message.js:39
    message.command = match[1];
                           ^
TypeError: Cannot read property '1' of null
    at parseMessage (/data/project/anon/anon/node_modules/wikichanges/node_modules/irc/lib/parse_message.js:39:28)
    at iterator (/data/project/anon/anon/node_modules/wikichanges/node_modules/irc/lib/irc.js:753:27)
    at Array.forEach (native)
    at Socket.Client.connect (/data/project/anon/anon/node_modules/wikichanges/node_modules/irc/lib/irc.js:752:15)
    at Socket.EventEmitter.emit (events.js:88:17)
    at TCP.onread (net.js:392:31)
```

In the past I've interpreted these as errors with Wikistream but I believe they are an error from the underlying irc library.

**Comment by jdcc** [comment]
Looks like it's this: https://github.com/martynsmith/node-irc/issues/325
