### ISSUE TITLE
parse message bug

### ISSUE THREAD

**Issue by edsu** [edsu/wikichanges#8]
```
/home/ed/Projects/anon/node_modules/wikichanges/node_modules/irc/lib/irc.js:672
                    throw err;
                          ^
TypeError: Cannot read property '1' of null
  at parse_msg (/home/ed/Projects/anon/node_modules/wikichanges/wikichanges.js:59:48)
  at Client.<anonymous> (/home/ed/Projects/anon/node_modules/wikichanges/wikichanges.js:32:15)
  at Client.EventEmitter.emit (events.js:106:17)
  at Client.<anonymous> (/home/ed/Projects/anon/node_modules/wikichanges/node_modules/irc/lib/irc.js:477:22)
  at Client.EventEmitter.emit (events.js:95:17)
  at /home/ed/Projects/anon/node_modules/wikichanges/node_modules/irc/lib/irc.js:669:22
  at Array.forEach (native)
  at Socket.<anonymous> (/home/ed/Projects/anon/node_modules/wikichanges/node_modules/irc/lib/irc.js:666:15)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)
```

**Comment by edsu** [comment]
fixed in [32d88d4e3f361a39add7ea54b60de2f008392b9c]
